export const GET_COORDINATES = 'GET_COORDINATES';
export const GET_COFFEE_SHOPS = 'GET_COFFEE_SHOPS';
export const GET_FAVORITES = 'GET_FAVORITES';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const ADD_NOTE = 'ADD_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';

